### ISSUE TITLE
dag_config not defined, cannot import example_variables.py

### ISSUE THREAD

**Issue by cjvandijk** [tuanavu/airflow-tutorial#21]
When I start the containers with docker-compose up, I get this error: ERROR - Failed to import: /usr/local/airflow/dags/example_variables.py

Then when I check to see what's up on localhost:8080, there are two dags showing but at the top is this error: Broken DAG: [/usr/local/airflow/dags/example_variables.py] name 'dag_config' is not defined

I see this file on my machine, but it is not in /usr/local/airflow (I'm on a mac). It's in airflow-tutorial⁩/⁨examples⁩/intro-example⁩/⁨dags⁩. I also see that docker-compose.yml defines this location that does not exist on my machine after using docker-compose to start the containers: 
   volumes:
      - ./examples/intro-example/dags:/usr/local/airflow/dags

What is the best way to correct this? Should I change the path under volumes: ? Even if I do, I think the example_variables.py comments out the line that assigns a value to dag_config. 

Thanks for any suggestions!

**Comment by tuanavu** [comment]
Hi @cjvandijk,

This issue has been asked and was resolved here: https://github.com/tuanavu/airflow-tutorial/issues/16, https://github.com/tuanavu/airflow-tutorial/issues/14

**Comment by hasandi** [comment]
Hi @tuanavu,

I have the same problem as @cjvandijk and I've already followed the solution of #16 by uploading the file to the Admin variables, but the error still exists.

Also I've noticed that the error is slightly different from #16. It's `NameError: name 'dag_config' is not defined`, not `Variable example_variables_config does not exist`.

Is there any steps that I've probably missed?

**Comment by ahuiberts** [comment]
Hi @tuanavu,

I got hte same problem as @hasandi. I got no solution ... Do you have suggestions?

**Comment by tuanavu** [comment]
Hi guys,

It was the mistake of this line:
https://github.com/tuanavu/airflow-tutorial/blob/5bddbf4625cb618d35b85054b9b10befe85dbae9/examples/intro-example/dags/example_variables.py#L47

I have reverted the commit to fix the issue. Basically, the `dag_config` is commented out which created the error you see: `NameError: name 'dag_config' is not defined`. Then you can follow https://github.com/tuanavu/airflow-tutorial/issues/16 to import the missing variable.

Also, please pull from a specific git tag so you have the correct code for the video tutorials you guys follow: https://github.com/tuanavu/airflow-tutorial#contents.

Best,
Tuan

**Comment by ahuiberts** [comment]
Thx a lot! Working fine now ....

**Comment by tuanavu** [comment]
Perfect, I am glad it is working for you.
